### ISSUE TITLE
Issue with instructions to install on OSX (macOS)

### ISSUE THREAD

**Issue by kkin1995** [Planet-Factory/claude#23]
From the documentation for macOS, I ran the following command after installing the dependencies:

```
python claude_setup.py build_ext --inplace
```
Which gave the following error:

```
claude_low_level_library.c:623:10: fatal error: 'numpy/arrayobject.h' file not found
#include "numpy/arrayobject.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
```

**Comment by anothersimulacrum** [comment]
You probably need to do something similar to [this bit from the linux instructions](https://github.com/Planet-Factory/claude/blob/master/BUILDING.md#some_other_fileh-no-such-file-or-directory).

**Comment by anothersimulacrum** [comment]
Try `find /usr/include/ -name "arrayobject.h"` to see if you have the correct header.

**Comment by kkin1995** [comment]
Yes! Thank You! The exact command that got it to work is:

```
python3 claude_setup.py build_ext --inplace -I/venv/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:venv/lib/python3.9/site-packages/numpy/core/include/
```

First, I found the location of "arrayobject.h" at the path 
```
/venv/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h
```
and then I found the location of numpy at the path
```
/venv/lib/python3.9/site-packages/numpy/core/include/
```
and included both of them in the command.
