### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by fernandocollova** [Planet-Factory/claude#26]
Hi,

I learned about this project in one of Simon Clark's latest videos, and looking at the repo, I wondered if this is like a private project of which the source code happens to be public, or if you guys are aiming for an "open source" kind of collaborative thing.

I'm asking because I was looking for a project that could help me brush up on my numpy skills, so I came here to see if there were any open issues I could work on, but as I found no license, and the project's goals look kind of narrow, I decided to create this issue.

Thanks, Fernando

**Comment by TechWizzart** [comment]
Hey Fernando,

How lovely that you want to contribute! In case you don't know this repository is for the development of a climate model, which is livestreamed on twitch every wednesday evening, 8 PM GMT. Then the code is updated and new functions are developed. As the TODO list is currently not public, it's very difficult for us as a community to contribute to the project, however if you think somethings in the code can be improved upon then feel free to improve them in a fork and create a pull request afterwards. Whether it will be adopted or not is up to Simon, but you can always try. 

As far as the license is concerned, I believe the admin team is working on that, though I cannot provide any insights as I'm not part of that team, perhaps that Captain Reid or ATGSilva knows more about this. 

Hope this clarifies some things.
- TechWizard

**Comment by anothersimulacrum** [comment]
> but as I found no license

This project appears to be licensed under the MIT license https://github.com/Planet-Factory/claude/blob/master/LICENSE.

**Comment by fernandocollova** [comment]
Oh, interesting, thanks for pointing it out! The readme had it listed as a todo, and I dindn't check
